# Generated by Django 5.1.8 on 2026-08-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_public_id_location_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('staff', 'Staff'), ('system', 'System')], max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('user_identity_id', models.UUIDField(blank=True, null=True)),
                ('staff_membership_id', models.UUIDField(blank=True, null=True)),
                ('membership_episode_id', models.UUIDField(blank=True, null=True)),
                ('authorization_generation', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('result', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied')], max_length=20)),
                ('permission', models.CharField(blank=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
