# Generated by Django 5.1.8 on 2026-08-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_public_id_location_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(max_length=20)),
                ('actor_id', models.CharField(max_length=64)),
                ('api_version', models.CharField(max_length=16)),
                ('method', models.CharField(max_length=10)),
                ('canonical_route', models.CharField(max_length=255)),
                ('idempotency_key_hash', models.CharField(max_length=64)),
                ('request_body_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('succeeded', 'Succeeded'), ('failed_final', 'Failed final')], max_length=20)),
                ('lease_expires_at', models.DateTimeField()),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_claims', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor_type', 'actor_id', 'tenant', 'api_version', 'method', 'canonical_route', 'idempotency_key_hash'), name='api_commandclaim_unique_key')],
            },
        ),
    ]
