# Generated by Django 5.1.8 on 2026-08-16 05:21

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_public_id_location_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MembershipEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('ended', 'Ended')], max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_episodes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['staff_membership_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='RoleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='identity.role')),
            ],
            options={
                'ordering': ['role_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='StaffMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('staff_number', models.CharField(max_length=32)),
                ('authorization_generation', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'staff_number'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(choices=[('tenant', 'Tenant'), ('location', 'Location')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='tenants.businesslocation')),
                ('membership_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='identity.membershipepisode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='tenants.tenant')),
                ('role_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='identity.roleversion')),
                ('staff_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='identity.staffmembership')),
            ],
            options={
                'ordering': ['staff_membership_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='membershipepisode',
            name='staff_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='identity.staffmembership'),
        ),
        migrations.CreateModel(
            name='LocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scope_type', models.CharField(choices=[('tenant', 'Tenant'), ('location', 'Location')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_assignments', to='tenants.businesslocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_assignments', to='tenants.tenant')),
                ('membership_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_assignments', to='identity.membershipepisode')),
                ('staff_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_assignments', to='identity.staffmembership')),
            ],
            options={
                'ordering': ['staff_membership_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_login', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['primary_login'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('primary_login'), name='identity_user_unique_login_lower')],
            },
        ),
        migrations.AddField(
            model_name='staffmembership',
            name='user_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_memberships', to='identity.useridentity'),
        ),
        migrations.AddConstraint(
            model_name='roleversion',
            constraint=models.UniqueConstraint(fields=('role', 'version'), name='identity_roleversion_unique_role_version'),
        ),
        migrations.AddConstraint(
            model_name='roleversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='identity_roleversion_version_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'tenant'), ('location__isnull', True)), models.Q(('scope_type', 'location'), ('location__isnull', False)), _connector='OR'), name='identity_role_assign_scope_location'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='identity_role_assign_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='membershipepisode',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='identity_episode_unique_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='membershipepisode',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['invited', 'active', 'suspended'])), fields=('staff_membership',), name='identity_episode_one_current'),
        ),
        migrations.AddConstraint(
            model_name='membershipepisode',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='identity_episode_version_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='membershipepisode',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='identity_episode_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='locationassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type', 'tenant'), ('location__isnull', True)), models.Q(('scope_type', 'location'), ('location__isnull', False)), _connector='OR'), name='identity_loc_assign_scope_location'),
        ),
        migrations.AddConstraint(
            model_name='locationassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='identity_loc_assign_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='staffmembership',
            constraint=models.UniqueConstraint(fields=('id', 'tenant'), name='identity_membership_unique_id_tenant'),
        ),
        migrations.AddConstraint(
            model_name='staffmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user_identity'), name='identity_membership_unique_tenant_identity'),
        ),
        migrations.AddConstraint(
            model_name='staffmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'staff_number'), name='identity_membership_unique_tenant_staff_number'),
        ),
        migrations.AddConstraint(
            model_name='staffmembership',
            constraint=models.CheckConstraint(condition=models.Q(('authorization_generation__gte', 0)), name='identity_membership_generation_gte_0'),
        ),
    ]
