# Generated by Django 5.1.8 on 2026-08-16 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.tenants.composite_fks import apply_session_foreign_keys, drop_session_foreign_keys


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_episode_membership_and_version'),
        ('tenants', '0002_public_id_location_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('authorization_generation', models.PositiveIntegerField()),
                ('token_prefix', models.CharField(max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_sessions', to='identity.membershipepisode')),
                ('staff_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_sessions', to='identity.staffmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_access_sessions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('id', 'tenant'), name='identity_session_unique_id_tenant'), models.UniqueConstraint(fields=('id', 'staff_membership', 'tenant'), name='identity_session_unique_id_membership_tenant')],
            },
        ),
        migrations.RunPython(apply_session_foreign_keys, drop_session_foreign_keys),
    ]
